services:

  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goodcollect_ocr
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 20s
    networks:
      - app_network

  # backend:
  #   container_name: fastapi
  #   build:
  #     context: ./backend
  #     dockerfile: backend.Dockerfile
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   ports:
  #     - 3004:3004
  #   environment:
  #     - DB_USER=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_HOST=postgres
  #   networks:
  #     - app_network
  
  # frontend:
  #   container_name: nextjs
  #   build:
  #     context: ./frontend
  #     dockerfile: frontend.Dockerfile
  #   env_file:
  #     - ./frontend/.env.local
  #   depends_on:
  #     - backend
  #     - proxygateway
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   networks:
  #     - app_network

  # proxygateway:
  #   container_name: krakend
  #   image: krakend:latest
  #   depends_on:
  #     - backend
  #   ports:
  #     - 8081:8080
  #   volumes:
  #     - ./krakend:/etc/krakend
  #   command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
  #   networks:
  #     - app_network
  
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "7770:9000"
      - "7771:9001"
    environment:
      MINIO_ROOT_USER: thomas@goodcollect.co
      MINIO_ROOT_PASSWORD: 9sdf7csdfsd89fsadfsdaFASDFa7cf7894sd987fcsd
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app_network

volumes:
  postgres_data:
  minio_data:

networks:
  app_network:
    driver: bridge
    