import pytest
import pytest_asyncio
from fastapi import FastAPI
from httpx import ASGITransport, AsyncClient

from application.containers.appContainer import AppContainer
from application.containers.buybackContainer import BuybackContainer
from infrastructure.routes import buyback as buyback_route_module


class FakeStorage:
    """Test double for the storage port returning a deterministic URL."""

    async def presigned_url(self, file_name, expires_in=3600):
        return f"https://storage.test/{file_name}?sig=abc"

    async def upload_file(self, *args, **kwargs):
        raise NotImplementedError

    async def download_file(self, *args, **kwargs):
        raise NotImplementedError

    async def delete_file(self, *args, **kwargs):
        raise NotImplementedError


@pytest_asyncio.fixture
async def client(session_factory):
    """Boots a minimal FastAPI app wired against the in-memory test database.

    The real AppContainer is used (providers are lazy, so no external resource
    is initialised), but its buyback sub-container is overridden to use the
    in-memory SQLite session factory and a fake storage strategy.
    """
    test_buyback_container = BuybackContainer(
        session=session_factory,
        storage=FakeStorage(),
    )

    container = AppContainer()
    container.buyback_container.override(test_buyback_container)

    app = FastAPI()
    app.include_router(buyback_route_module.buyback_routes())

    container.wire(modules=[buyback_route_module])

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        yield ac

    container.buyback_container.reset_override()
    container.unwire()


@pytest.mark.asyncio
async def test_post_creates_persists_and_returns_buybacks(client):
    payload = [
        {"gc_booking": "B-123", "amount": 100, "currency": "EUR"},
        {"gc_booking": "B-456", "amount": 200, "currency": "EUR"},
    ]

    resp = await client.post("/client/buyback/creates", json=payload)

    assert resp.status_code == 201
    body = resp.json()
    assert body["status_code"] == 201
    assert len(body["data"]) == 2

    amounts = sorted(item["amount"] for item in body["data"])
    assert amounts == [100, 200]
    for item in body["data"]:
        assert item["id"]  # generated by the DB layer
        assert item["created_at"]


@pytest.mark.asyncio
async def test_post_creates_rejects_empty_body(client):
    resp = await client.post("/client/buyback/creates", json=[])

    assert resp.status_code == 422
    assert resp.json()["data"] is None


@pytest.mark.asyncio
async def test_post_creates_rejects_invalid_payload(client):
    # negative amount + invalid currency -> Pydantic validation (HTTP 422)
    resp = await client.post(
        "/client/buyback/creates",
        json=[{"amount": -5, "currency": "JPY"}],
    )

    assert resp.status_code == 422


@pytest.mark.asyncio
async def test_get_all_returns_empty_list_when_no_buybacks(client):
    resp = await client.get("/client/buyback/all")

    assert resp.status_code == 201
    body = resp.json()
    assert body["status_code"] == 201
    assert body["data"]["items"] == []
    assert body["data"]["total"] == 0


@pytest.mark.asyncio
async def test_get_all_returns_persisted_buybacks(client):
    payload = [
        {"gc_booking": "B-123", "amount": 100, "currency": "EUR"},
        {"gc_booking": "B-456", "amount": 200, "currency": "EUR"},
    ]
    create_resp = await client.post("/client/buyback/creates", json=payload)
    assert create_resp.status_code == 201

    resp = await client.get("/client/buyback/all")

    assert resp.status_code == 201
    body = resp.json()
    assert body["status_code"] == 201
    items = body["data"]["items"]
    assert len(items) == 2
    assert body["data"]["total"] == 2
    amounts = sorted(item["amount"] for item in items)
    assert amounts == [100, 200]
    for item in items:
        assert item["id"]
        assert item["created_at"]


async def _seed_buyback(session_factory, *, file_path=None) -> str:
    """Insert a buyback directly and return its generated id."""
    from domain.models.buyback import Buyback
    from domain.models.enums import StatusBuyBackEnum

    buyback = Buyback(
        amount=150,
        status=StatusBuyBackEnum.TO_BE_TRAITED.value,
        gc_booking="B-999",
        file_path=file_path,
    )
    async with session_factory() as session:
        async with session.begin():
            session.add(buyback)
        await session.refresh(buyback)
        return buyback.id


@pytest.mark.asyncio
async def test_get_by_id_without_document_returns_200_and_no_url(
    client, session_factory
):
    buyback_id = await _seed_buyback(session_factory, file_path=None)

    resp = await client.get(f"/client/buyback/{buyback_id}")

    assert resp.status_code == 200
    body = resp.json()
    assert body["status_code"] == 200
    assert body["data"]["id"] == buyback_id
    assert body["data"]["document"] is None


@pytest.mark.asyncio
async def test_get_by_id_with_document_returns_presigned_url(
    client, session_factory
):
    storage_key = "buyback/some-file.pdf"
    buyback_id = await _seed_buyback(session_factory, file_path=storage_key)

    resp = await client.get(f"/client/buyback/{buyback_id}")

    assert resp.status_code == 200
    body = resp.json()
    assert body["status_code"] == 200
    document = body["data"]["document"]
    assert document is not None
    assert document["storage_key"] == storage_key
    assert document["url"] == f"https://storage.test/{storage_key}?sig=abc"


@pytest.mark.asyncio
async def test_get_by_id_not_found_returns_404(client):
    resp = await client.get("/client/buyback/BBdoesnotexist")

    assert resp.status_code == 404
    body = resp.json()
    assert body["status_code"] == 404
    assert body["data"] is None
