"""add indexes on invoices

Revision ID: 14a3c1b31d42
Revises: a9b85fc8c11f
Create Date: 2026-02-17 14:42:58.845672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14a3c1b31d42'
down_revision: Union[str, Sequence[str], None] = 'a9b85fc8c11f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_invoices_created_at_id', 'invoice', ['created_at', 'id'], unique=False)
    op.create_index('ix_invoices_status_created_at_id', 'invoice', ['status', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoices_status_created_at_id', table_name='invoice')
    op.drop_index('ix_invoices_created_at_id', table_name='invoice')