"""Add invoice search vector

Revision ID: 1f1948c3e5c7
Revises: 5c17de1e163a
Create Date: 2026-07-28 21:41:30.115548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f1948c3e5c7'
down_revision: Union[str, Sequence[str], None] = '5c17de1e163a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_invoice_search_vector', 'invoice', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoice_search_vector', table_name='invoice', postgresql_using='gin')
    op.drop_column('invoice', 'search_vector')
    # ### end Alembic commands ###
