"""Init Data Modeling

Revision ID: 5c17de1e163a
Revises: 
Create Date: 2026-07-28 21:34:50.079717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c17de1e163a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'buyback', ['id'])
    op.create_unique_constraint(None, 'invoice', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'workflow', ['id'])
    op.create_unique_constraint(None, 'workflow_step', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_step', type_='unique')
    op.drop_constraint(None, 'workflow', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'invoice', type_='unique')
    op.drop_constraint(None, 'buyback', type_='unique')
    # ### end Alembic commands ###
