"""Remove relation between buyback and invoice

Revision ID: 9924965b999f
Revises: 898c827c5ac0
Create Date: 2026-07-03 09:34:42.284132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9924965b999f'
down_revision: Union[str, Sequence[str], None] = '898c827c5ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'buyback', ['id'])
    op.drop_column('buyback', 'invoice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyback', sa.Column('invoice_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'buyback', type_='unique')
    # ### end Alembic commands ###
