"""add search_vector to

Revision ID: bb4ce4bad70c
Revises: 0130dccf0b42
Create Date: 2026-07-05 21:23:24.285881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'bb4ce4bad70c'
down_revision: Union[str, Sequence[str], None] = '0130dccf0b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Ajouter la colonne tsvector
    op.add_column(
        "invoice",
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True)
    )

    # 2. Créer index GIN pour performance
    op.create_index(
        "ix_invoice_search_vector",
        "invoice",
        ["search_vector"],
        postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_invoice_search_vector", table_name="invoice")
    op.drop_column("invoice", "search_vector")
    # ### end Alembic commands ###
