"""add new invoice.crm_id field

Revision ID: c9faa38b87e5
Revises: ddbdcecb5444
Create Date: 2026-08-10 22:47:36.366493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9faa38b87e5'
down_revision: Union[str, Sequence[str], None] = 'ddbdcecb5444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'buyback', ['id'])
    op.add_column('invoice', sa.Column('crm_id', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('invoice_external_id_key'), 'invoice', type_='unique')
    op.create_unique_constraint(None, 'invoice', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'workflow', ['id'])
    op.create_unique_constraint(None, 'workflow_step', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_step', type_='unique')
    op.drop_constraint(None, 'workflow', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'invoice', type_='unique')
    op.create_unique_constraint(op.f('invoice_external_id_key'), 'invoice', ['external_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('invoice', 'crm_id')
    op.drop_constraint(None, 'buyback', type_='unique')
    # ### end Alembic commands ###
