"""Add amount column buybak

Revision ID: 0130dccf0b42
Revises: 9924965b999f
Create Date: 2026-07-03 10:54:46.885380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0130dccf0b42'
down_revision: Union[str, Sequence[str], None] = '9924965b999f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyback', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buyback', 'amount')
    # ### end Alembic commands ###
