"""backfill search_vector + add trigger

Revision ID: 5bfd47935906
Revises: bb4ce4bad70c
Create Date: 2026-07-05 21:26:26.309737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bfd47935906'
down_revision: Union[str, Sequence[str], None] = 'bb4ce4bad70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE invoice
        SET search_vector =
            to_tsvector(
                'simple',
                coalesce(name,'') || ' ' ||
                coalesce(invoice_number,'') || ' ' ||
                coalesce(external_id,'') || ' ' ||
                coalesce(issuer_name,'')
            );
    """)

    # 2. Trigger auto-update
    op.execute("""
        CREATE OR REPLACE FUNCTION invoice_search_vector_update()
        RETURNS trigger AS $$
        BEGIN
          NEW.search_vector :=
            to_tsvector(
              'simple',
              coalesce(NEW.name,'') || ' ' ||
              coalesce(NEW.invoice_number,'') || ' ' ||
              coalesce(NEW.external_id,'') || ' ' ||
              coalesce(NEW.issuer_name,'')
            );
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER trg_invoice_search
        BEFORE INSERT OR UPDATE ON invoice
        FOR EACH ROW
        EXECUTE FUNCTION invoice_search_vector_update();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_invoice_search ON invoice;")
    op.execute("DROP FUNCTION IF EXISTS invoice_search_vector_update;")
    # ### end Alembic commands ###
